# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1540, 873)
        MainWindow.setStyleSheet("QWidget{\n"
"    \n"
"    background-color:rgb(255, 255, 255);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.header = QtWidgets.QWidget(self.centralwidget)
        self.header.setStyleSheet("#header{\n"
"\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.header.setObjectName("header")
        self.horizontalLayout.addWidget(self.header)
        self.functionFrame = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.functionFrame.sizePolicy().hasHeightForWidth())
        self.functionFrame.setSizePolicy(sizePolicy)
        self.functionFrame.setStyleSheet("QWidget{\n"
"    border: 2px solid ;\n"
"    border-color : None rgb(0, 0, 0) None None;\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    border: 2px solid rgb(0, 154, 206)\n"
"    \n"
"}\n"
"QPushButton:focus{\n"
"    border: 2px solid rgb(0, 154, 206)\n"
"    \n"
"}\n"
"\n"
"")
        self.functionFrame.setObjectName("functionFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.functionFrame)
        self.verticalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.rotateButton = QtWidgets.QPushButton(self.functionFrame)
        self.rotateButton.setEnabled(True)
        self.rotateButton.setMinimumSize(QtCore.QSize(150, 50))
        self.rotateButton.setMaximumSize(QtCore.QSize(150, 50))
        self.rotateButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotateButton.setIcon(icon)
        self.rotateButton.setCheckable(False)
        self.rotateButton.setChecked(False)
        self.rotateButton.setAutoDefault(False)
        self.rotateButton.setDefault(False)
        self.rotateButton.setObjectName("rotateButton")
        self.verticalLayout_4.addWidget(self.rotateButton)
        self.drawButton = QtWidgets.QPushButton(self.functionFrame)
        self.drawButton.setMinimumSize(QtCore.QSize(150, 50))
        self.drawButton.setMaximumSize(QtCore.QSize(150, 50))
        self.drawButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/pencil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.drawButton.setIcon(icon1)
        self.drawButton.setObjectName("drawButton")
        self.verticalLayout_4.addWidget(self.drawButton)
        self.filterButton = QtWidgets.QPushButton(self.functionFrame)
        self.filterButton.setMinimumSize(QtCore.QSize(150, 50))
        self.filterButton.setMaximumSize(QtCore.QSize(150, 50))
        self.filterButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/filter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.filterButton.setIcon(icon2)
        self.filterButton.setObjectName("filterButton")
        self.verticalLayout_4.addWidget(self.filterButton)
        self.effectButton = QtWidgets.QPushButton(self.functionFrame)
        self.effectButton.setMinimumSize(QtCore.QSize(150, 50))
        self.effectButton.setMaximumSize(QtCore.QSize(150, 50))
        self.effectButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/effect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.effectButton.setIcon(icon3)
        self.effectButton.setObjectName("effectButton")
        self.verticalLayout_4.addWidget(self.effectButton)
        self.advancedButton = QtWidgets.QPushButton(self.functionFrame)
        self.advancedButton.setMinimumSize(QtCore.QSize(150, 50))
        self.advancedButton.setMaximumSize(QtCore.QSize(150, 50))
        self.advancedButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon/file-ai.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.advancedButton.setIcon(icon4)
        self.advancedButton.setObjectName("advancedButton")
        self.verticalLayout_4.addWidget(self.advancedButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.drawApplyPushButton = QtWidgets.QPushButton(self.functionFrame)
        self.drawApplyPushButton.setMinimumSize(QtCore.QSize(150, 50))
        self.drawApplyPushButton.setMaximumSize(QtCore.QSize(150, 50))
        self.drawApplyPushButton.setStyleSheet("QPushButton{\n"
"    background-color : rgb(34, 84, 244);\n"
"    color : rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"QPushButton:pressed{\n"
"\n"
"border:2px solid;\n"
"background-color : rgb(255, 255, 255);\n"
"    color : rgb(34, 84, 244);\n"
"}")
        self.drawApplyPushButton.setObjectName("drawApplyPushButton")
        self.verticalLayout_4.addWidget(self.drawApplyPushButton)
        self.verticalLayout_4.setStretch(3, 1)
        self.verticalLayout_4.setStretch(5, 7)
        self.horizontalLayout.addWidget(self.functionFrame)
        self.actionWidget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.actionWidget.sizePolicy().hasHeightForWidth())
        self.actionWidget.setSizePolicy(sizePolicy)
        self.actionWidget.setStyleSheet("QWidget#actionWidget{\n"
"    border: 2px solid ;\n"
"    border-color : None rgb(0, 0, 0) None None;\n"
"}")
        self.actionWidget.setObjectName("actionWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.actionWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 10, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.actionWidget)
        self.stackedWidget.setStyleSheet("QPushButton{\n"
"\n"
"    border:none;\n"
"    background-color:rgb(255, 255, 255);\n"
"    color: black; \n"
"    font: 10pt  \'Arial\';\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    border: 2px solid rgb(0, 154, 206)\n"
"}\n"
"QLabel{\n"
"\n"
"    color: black; \n"
"    font: 10pt  \'Arial\'; \n"
"}\n"
"QCheckBox{\n"
"color: black; \n"
"font: 10pt  \'Arial\'; \n"
"\n"
"}\n"
"QLineEdit{\n"
"\n"
"    color: black; \n"
"    font: 10pt  \'Arial\'; \n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.rotatePage = QtWidgets.QWidget()
        self.rotatePage.setObjectName("rotatePage")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.rotatePage)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.rotatePage)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.widthLineEdit = QtWidgets.QLineEdit(self.rotatePage)
        self.widthLineEdit.setObjectName("widthLineEdit")
        self.horizontalLayout_2.addWidget(self.widthLineEdit)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 10, -1, 20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.rotatePage)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.heightLineEdit = QtWidgets.QLineEdit(self.rotatePage)
        self.heightLineEdit.setObjectName("heightLineEdit")
        self.horizontalLayout_3.addWidget(self.heightLineEdit)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 2)
        self.horizontalLayout_3.setStretch(2, 1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.fixScaleCheckBox = QtWidgets.QCheckBox(self.rotatePage)
        self.fixScaleCheckBox.setObjectName("fixScaleCheckBox")
        self.verticalLayout_3.addWidget(self.fixScaleCheckBox)
        self.sizePushButton = QtWidgets.QPushButton(self.rotatePage)
        self.sizePushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.sizePushButton.setMaximumSize(QtCore.QSize(100, 30))
        self.sizePushButton.setStyleSheet("QPushButton{\n"
"    border:2px solid;\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"    border: 2px solid rgb(0, 154, 206)\n"
"}")
        self.sizePushButton.setObjectName("sizePushButton")
        self.verticalLayout_3.addWidget(self.sizePushButton)
        self.horizontalLayout_16.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, 20, -1, 50)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.rotateRight = QtWidgets.QPushButton(self.rotatePage)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon/rotate-right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotateRight.setIcon(icon5)
        self.rotateRight.setIconSize(QtCore.QSize(30, 30))
        self.rotateRight.setObjectName("rotateRight")
        self.horizontalLayout_4.addWidget(self.rotateRight)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.rotateLeft = QtWidgets.QPushButton(self.rotatePage)
        self.rotateLeft.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icon/rotate-left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rotateLeft.setIcon(icon6)
        self.rotateLeft.setIconSize(QtCore.QSize(30, 30))
        self.rotateLeft.setObjectName("rotateLeft")
        self.horizontalLayout_4.addWidget(self.rotateLeft)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.horizontalPushButton = QtWidgets.QPushButton(self.rotatePage)
        self.horizontalPushButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icon/hflip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.horizontalPushButton.setIcon(icon7)
        self.horizontalPushButton.setIconSize(QtCore.QSize(30, 30))
        self.horizontalPushButton.setObjectName("horizontalPushButton")
        self.horizontalLayout_4.addWidget(self.horizontalPushButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalPushButton = QtWidgets.QPushButton(self.rotatePage)
        self.verticalPushButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/icon/vflip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.verticalPushButton.setIcon(icon8)
        self.verticalPushButton.setIconSize(QtCore.QSize(30, 30))
        self.verticalPushButton.setObjectName("verticalPushButton")
        self.horizontalLayout_4.addWidget(self.verticalPushButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem7)
        self.cropPushButton = QtWidgets.QPushButton(self.rotatePage)
        self.cropPushButton.setMinimumSize(QtCore.QSize(150, 30))
        self.cropPushButton.setMaximumSize(QtCore.QSize(150, 30))
        self.cropPushButton.setStyleSheet("QPushButton{\n"
"    border:2px solid rgb(255, 255, 255);\n"
"    background-color:rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"    border: 2px solid rgb(0, 154, 206)\n"
"}")
        self.cropPushButton.setObjectName("cropPushButton")
        self.horizontalLayout_27.addWidget(self.cropPushButton)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_27)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.stackedWidget.addWidget(self.rotatePage)
        self.drawPage = QtWidgets.QWidget()
        self.drawPage.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background-color:rgb(255, 255, 255);\n"
"}\n"
"")
        self.drawPage.setObjectName("drawPage")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.drawPage)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.colorLabel_2 = QtWidgets.QLabel(self.drawPage)
        self.colorLabel_2.setObjectName("colorLabel_2")
        self.verticalLayout_8.addWidget(self.colorLabel_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(10, 10, 10, 50)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(50)
        self.gridLayout.setObjectName("gridLayout")
        self.lineRadioButton = QtWidgets.QRadioButton(self.drawPage)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/icon/line.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lineRadioButton.setIcon(icon9)
        self.lineRadioButton.setIconSize(QtCore.QSize(40, 40))
        self.lineRadioButton.setObjectName("lineRadioButton")
        self.gridLayout.addWidget(self.lineRadioButton, 2, 1, 1, 1)
        self.rectRadioButton = QtWidgets.QRadioButton(self.drawPage)
        self.rectRadioButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/icon/rectangle-horizontal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rectRadioButton.setIcon(icon10)
        self.rectRadioButton.setIconSize(QtCore.QSize(30, 30))
        self.rectRadioButton.setChecked(False)
        self.rectRadioButton.setObjectName("rectRadioButton")
        self.gridLayout.addWidget(self.rectRadioButton, 2, 0, 1, 1)
        self.brushRadioButton = QtWidgets.QRadioButton(self.drawPage)
        self.brushRadioButton.setEnabled(True)
        self.brushRadioButton.setMouseTracking(True)
        self.brushRadioButton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon/icon/paint-brush.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brushRadioButton.setIcon(icon11)
        self.brushRadioButton.setIconSize(QtCore.QSize(30, 30))
        self.brushRadioButton.setCheckable(True)
        self.brushRadioButton.setChecked(True)
        self.brushRadioButton.setObjectName("brushRadioButton")
        self.gridLayout.addWidget(self.brushRadioButton, 1, 0, 1, 1)
        self.eplipseRadioButton = QtWidgets.QRadioButton(self.drawPage)
        self.eplipseRadioButton.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icon/icon/rec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eplipseRadioButton.setIcon(icon12)
        self.eplipseRadioButton.setIconSize(QtCore.QSize(30, 30))
        self.eplipseRadioButton.setObjectName("eplipseRadioButton")
        self.gridLayout.addWidget(self.eplipseRadioButton, 1, 1, 1, 1)
        self.pieRadioButton = QtWidgets.QRadioButton(self.drawPage)
        self.pieRadioButton.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icon/icon/chart-pie-alt.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pieRadioButton.setIcon(icon13)
        self.pieRadioButton.setIconSize(QtCore.QSize(30, 30))
        self.pieRadioButton.setObjectName("pieRadioButton")
        self.gridLayout.addWidget(self.pieRadioButton, 3, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(0, 0, 0, 50)
        self.horizontalLayout_21.setSpacing(0)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.penStyleComboBox = QtWidgets.QComboBox(self.drawPage)
        self.penStyleComboBox.setStyleSheet("QComboBox{\n"
"\n"
"    color: black; \n"
"    font: 10pt  \'Arial\'; \n"
"}")
        self.penStyleComboBox.setObjectName("penStyleComboBox")
        self.penStyleComboBox.addItem("")
        self.penStyleComboBox.addItem("")
        self.penStyleComboBox.addItem("")
        self.horizontalLayout_21.addWidget(self.penStyleComboBox)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem10)
        self.verticalLayout_8.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 50)
        self.horizontalLayout_8.setSpacing(10)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.drawPage)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.penSizeHorizontalSlider = QtWidgets.QSlider(self.drawPage)
        self.penSizeHorizontalSlider.setMaximum(25)
        self.penSizeHorizontalSlider.setSliderPosition(5)
        self.penSizeHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.penSizeHorizontalSlider.setObjectName("penSizeHorizontalSlider")
        self.horizontalLayout_8.addWidget(self.penSizeHorizontalSlider)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem11)
        self.penSizeLineEdit = QtWidgets.QLineEdit(self.drawPage)
        self.penSizeLineEdit.setStyleSheet("QLineEdit{\n"
"\n"
"    color: black; \n"
"    font: 10pt  \'Arial\'; \n"
"}")
        self.penSizeLineEdit.setObjectName("penSizeLineEdit")
        self.horizontalLayout_8.addWidget(self.penSizeLineEdit)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 3)
        self.horizontalLayout_8.setStretch(2, 8)
        self.horizontalLayout_8.setStretch(3, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.colorLabel = QtWidgets.QLabel(self.drawPage)
        self.colorLabel.setObjectName("colorLabel")
        self.horizontalLayout_6.addWidget(self.colorLabel)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem12)
        self.colorPickPushButton = QtWidgets.QPushButton(self.drawPage)
        self.colorPickPushButton.setMinimumSize(QtCore.QSize(200, 20))
        self.colorPickPushButton.setMaximumSize(QtCore.QSize(200, 20))
        self.colorPickPushButton.setStyleSheet("QPushButton {\n"
" \n"
"    border-style: outset;\n"
"    padding: 2px;\n"
"    font: bold 20px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: black;\n"
"}")
        self.colorPickPushButton.setText("")
        self.colorPickPushButton.setObjectName("colorPickPushButton")
        self.horizontalLayout_6.addWidget(self.colorPickPushButton)
        self.horizontalLayout_6.setStretch(0, 1)
        self.horizontalLayout_6.setStretch(1, 8)
        self.horizontalLayout_6.setStretch(2, 1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_6)
        spacerItem13 = QtWidgets.QSpacerItem(20, 237, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem13)
        self.stackedWidget.addWidget(self.drawPage)
        self.effectPage = QtWidgets.QWidget()
        self.effectPage.setStyleSheet("QPushButton{\n"
"    border: 1px solid \n"
"    \n"
"}")
        self.effectPage.setObjectName("effectPage")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.effectPage)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.effectPage)
        self.scrollArea.setMinimumSize(QtCore.QSize(500, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 626, 1132))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setStyleSheet("QPushButton:focus{\n"
"\n"
"    background-color:rgb(219, 255, 231);\n"
"}\n"
"")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setSpacing(10)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.brightnessPushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.brightnessPushButton.setMinimumSize(QtCore.QSize(150, 150))
        self.brightnessPushButton.setMaximumSize(QtCore.QSize(150, 150))
        self.brightnessPushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-image:url(:/effectImage/effectImage/bright.jpg);\n"
"\n"
"}")
        self.brightnessPushButton.setObjectName("brightnessPushButton")
        self.gridLayout_2.addWidget(self.brightnessPushButton, 1, 1, 1, 1)
        self.pencilColorPushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pencilColorPushButton.setMinimumSize(QtCore.QSize(150, 150))
        self.pencilColorPushButton.setMaximumSize(QtCore.QSize(150, 150))
        self.pencilColorPushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-image:url(:/effectImage/effectImage/pencil_col.jpg);\n"
"\n"
"}")
        self.pencilColorPushButton.setObjectName("pencilColorPushButton")
        self.gridLayout_2.addWidget(self.pencilColorPushButton, 5, 1, 1, 1)
        self.gaussianBlurPushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.gaussianBlurPushButton.setMinimumSize(QtCore.QSize(150, 150))
        self.gaussianBlurPushButton.setMaximumSize(QtCore.QSize(150, 150))
        self.gaussianBlurPushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-image:url(:/effectImage/effectImage/gausBlur.jpg);\n"
"\n"
"}")
        self.gaussianBlurPushButton.setObjectName("gaussianBlurPushButton")
        self.gridLayout_2.addWidget(self.gaussianBlurPushButton, 6, 1, 1, 1)
        self.medianBlurPushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.medianBlurPushButton.setMinimumSize(QtCore.QSize(150, 150))
        self.medianBlurPushButton.setMaximumSize(QtCore.QSize(150, 150))
        self.medianBlurPushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-image:url(:/effectImage/effectImage/median.jpg);\n"
"\n"
"}")
        self.medianBlurPushButton.setObjectName("medianBlurPushButton")
        self.gridLayout_2.addWidget(self.medianBlurPushButton, 6, 0, 1, 1)
        self.sharpPushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.sharpPushButton.setMinimumSize(QtCore.QSize(150, 150))
        self.sharpPushButton.setMaximumSize(QtCore.QSize(150, 150))
        self.sharpPushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-image:url(:/effectImage/effectImage/sharpen.jpg);\n"
"\n"
"}")
        self.sharpPushButton.setObjectName("sharpPushButton")
        self.gridLayout_2.addWidget(self.sharpPushButton, 2, 1, 1, 1)
        self.originalPushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.originalPushButton.setMinimumSize(QtCore.QSize(150, 150))
        self.originalPushButton.setMaximumSize(QtCore.QSize(150, 150))
        self.originalPushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-image:url(:/effectImage/effectImage/ori.jpg);\n"
"\n"
"}")
        self.originalPushButton.setObjectName("originalPushButton")
        self.gridLayout_2.addWidget(self.originalPushButton, 0, 0, 1, 1)
        self.foilPushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.foilPushButton.setMinimumSize(QtCore.QSize(150, 150))
        self.foilPushButton.setMaximumSize(QtCore.QSize(150, 150))
        self.foilPushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-image:url(:/effectImage/effectImage/foil.jpg);\n"
"\n"
"}")
        self.foilPushButton.setObjectName("foilPushButton")
        self.gridLayout_2.addWidget(self.foilPushButton, 5, 0, 1, 1)
        self.invertPushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.invertPushButton.setMinimumSize(QtCore.QSize(150, 150))
        self.invertPushButton.setMaximumSize(QtCore.QSize(150, 150))
        self.invertPushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-image:url(:/effectImage/effectImage/invert.jpg);\n"
"\n"
"}")
        self.invertPushButton.setObjectName("invertPushButton")
        self.gridLayout_2.addWidget(self.invertPushButton, 4, 1, 1, 1)
        self.sepiaPushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.sepiaPushButton.setMinimumSize(QtCore.QSize(150, 150))
        self.sepiaPushButton.setMaximumSize(QtCore.QSize(150, 150))
        self.sepiaPushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-image:url(:/effectImage/effectImage/sepia.jpg);\n"
"\n"
"}")
        self.sepiaPushButton.setObjectName("sepiaPushButton")
        self.gridLayout_2.addWidget(self.sepiaPushButton, 4, 0, 1, 1)
        self.summerPushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.summerPushButton.setMinimumSize(QtCore.QSize(150, 150))
        self.summerPushButton.setMaximumSize(QtCore.QSize(150, 150))
        self.summerPushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-image:url(:/effectImage/effectImage/summer.jpg);\n"
"\n"
"}")
        self.summerPushButton.setObjectName("summerPushButton")
        self.gridLayout_2.addWidget(self.summerPushButton, 3, 1, 1, 1)
        self.winterPushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.winterPushButton.setMinimumSize(QtCore.QSize(150, 150))
        self.winterPushButton.setMaximumSize(QtCore.QSize(150, 150))
        self.winterPushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-image:url(:/effectImage/effectImage/winter.jpg);\n"
"\n"
"}")
        self.winterPushButton.setObjectName("winterPushButton")
        self.gridLayout_2.addWidget(self.winterPushButton, 3, 0, 1, 1)
        self.greyScalePushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.greyScalePushButton.setMinimumSize(QtCore.QSize(150, 150))
        self.greyScalePushButton.setMaximumSize(QtCore.QSize(150, 150))
        self.greyScalePushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-image:url(:/effectImage/effectImage/greyscale.jpg);\n"
"\n"
"}")
        self.greyScalePushButton.setObjectName("greyScalePushButton")
        self.gridLayout_2.addWidget(self.greyScalePushButton, 2, 0, 1, 1)
        self.darkerPushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.darkerPushButton.setMinimumSize(QtCore.QSize(150, 150))
        self.darkerPushButton.setMaximumSize(QtCore.QSize(150, 150))
        self.darkerPushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-image:url(:/effectImage/effectImage/drak.jpg);\n"
"\n"
"}")
        self.darkerPushButton.setObjectName("darkerPushButton")
        self.gridLayout_2.addWidget(self.darkerPushButton, 1, 0, 1, 1)
        self.hdrPushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.hdrPushButton.setMinimumSize(QtCore.QSize(150, 150))
        self.hdrPushButton.setMaximumSize(QtCore.QSize(150, 150))
        self.hdrPushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-image:url(:/effectImage/effectImage/HDR.jpg);\n"
"\n"
"}")
        self.hdrPushButton.setObjectName("hdrPushButton")
        self.gridLayout_2.addWidget(self.hdrPushButton, 0, 1, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 4, 1, 1, 1)
        self.stackedWidget.addWidget(self.effectPage)
        self.filterPage = QtWidgets.QWidget()
        self.filterPage.setObjectName("filterPage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.filterPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.toolBox = QtWidgets.QToolBox(self.filterPage)
        self.toolBox.setStyleSheet("QToolBox{\n"
"\n"
"    color: black; \n"
"    font: 10pt  \'Arial\'; \n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 197, 326))
        self.page.setObjectName("page")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_18.setSpacing(20)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(10)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.page)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_12.addWidget(self.label_5)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem14)
        self.contrastLineEdit = QtWidgets.QLineEdit(self.page)
        self.contrastLineEdit.setObjectName("contrastLineEdit")
        self.horizontalLayout_12.addWidget(self.contrastLineEdit)
        self.horizontalLayout_12.setStretch(0, 1)
        self.horizontalLayout_12.setStretch(1, 8)
        self.horizontalLayout_12.setStretch(2, 1)
        self.verticalLayout_12.addLayout(self.horizontalLayout_12)
        self.contraseHorizontalSlider = QtWidgets.QSlider(self.page)
        self.contraseHorizontalSlider.setMinimum(1)
        self.contraseHorizontalSlider.setMaximum(10)
        self.contraseHorizontalSlider.setSliderPosition(1)
        self.contraseHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.contraseHorizontalSlider.setObjectName("contraseHorizontalSlider")
        self.verticalLayout_12.addWidget(self.contraseHorizontalSlider)
        self.verticalLayout_18.addLayout(self.verticalLayout_12)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setSpacing(10)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_12 = QtWidgets.QLabel(self.page)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_17.addWidget(self.label_12)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem15)
        self.hueLineEdit = QtWidgets.QLineEdit(self.page)
        self.hueLineEdit.setObjectName("hueLineEdit")
        self.horizontalLayout_17.addWidget(self.hueLineEdit)
        self.horizontalLayout_17.setStretch(0, 1)
        self.horizontalLayout_17.setStretch(1, 8)
        self.horizontalLayout_17.setStretch(2, 1)
        self.verticalLayout_16.addLayout(self.horizontalLayout_17)
        self.hueHorizontalSlider = QtWidgets.QSlider(self.page)
        self.hueHorizontalSlider.setMinimum(-50)
        self.hueHorizontalSlider.setMaximum(50)
        self.hueHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.hueHorizontalSlider.setObjectName("hueHorizontalSlider")
        self.verticalLayout_16.addWidget(self.hueHorizontalSlider)
        self.verticalLayout_18.addLayout(self.verticalLayout_16)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setSpacing(10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_6 = QtWidgets.QLabel(self.page)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_9.addWidget(self.label_6)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem16)
        self.brightnessLineEdit = QtWidgets.QLineEdit(self.page)
        self.brightnessLineEdit.setPlaceholderText("")
        self.brightnessLineEdit.setObjectName("brightnessLineEdit")
        self.horizontalLayout_9.addWidget(self.brightnessLineEdit)
        self.horizontalLayout_9.setStretch(0, 1)
        self.horizontalLayout_9.setStretch(1, 8)
        self.horizontalLayout_9.setStretch(2, 1)
        self.verticalLayout_9.addLayout(self.horizontalLayout_9)
        self.brightnessHorizontalSlider = QtWidgets.QSlider(self.page)
        self.brightnessHorizontalSlider.setMinimum(-100)
        self.brightnessHorizontalSlider.setMaximum(100)
        self.brightnessHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brightnessHorizontalSlider.setObjectName("brightnessHorizontalSlider")
        self.verticalLayout_9.addWidget(self.brightnessHorizontalSlider)
        self.verticalLayout_18.addLayout(self.verticalLayout_9)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSpacing(10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.page)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem17)
        self.saturationLineEdit = QtWidgets.QLineEdit(self.page)
        self.saturationLineEdit.setInputMask("")
        self.saturationLineEdit.setObjectName("saturationLineEdit")
        self.horizontalLayout_10.addWidget(self.saturationLineEdit)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 8)
        self.horizontalLayout_10.setStretch(2, 1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.saturationHorizontalSlider = QtWidgets.QSlider(self.page)
        self.saturationHorizontalSlider.setMinimum(-100)
        self.saturationHorizontalSlider.setMaximum(100)
        self.saturationHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.saturationHorizontalSlider.setObjectName("saturationHorizontalSlider")
        self.verticalLayout_11.addWidget(self.saturationHorizontalSlider)
        self.verticalLayout_18.addLayout(self.verticalLayout_11)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 606, 391))
        self.page_2.setStyleSheet("\n"
"QSlider::groove:vertical\n"
"{\n"
"    width: 5px;\n"
"    background: #C0C0C0;\n"
"    border: 1px solid #4A708B;\n"
"    border-radius: 1px;\n"
"    padding-left:-1px;\n"
"    padding-right:-1px;\n"
"    padding-top:-1px;\n"
"    padding-bottom:-1px;\n"
"}\n"
"\n"
"QSlider::sub-page:vertical\n"
"{\n"
"    background: #575757;\n"
"    border: 1px solid #4A708B;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical\n"
"{\n"
"    width: 10px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #c4c4c4, stop:1 #B1B1B1);\n"
"    background: qlineargradient(x1:0, y1:0.2, x2:1, y2:1, stop:0 #5DCCFF, stop: 1 #1874CD);\n"
"    border: 0px solid #777;\n"
"    border-radius: 2px;\n"
"}\n"
"\n"
"QSlider::handle:vertical \n"
"{\n"
"    height: 11px;\n"
"    background: qradialgradient\n"
"    (\n"
"        spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, \n"
"        stop:0.6 #45ADED, stop:0.778409 rgba(255, 255, 255, 255)\n"
"    );\n"
"    margin-left: -3px;\n"
"    margin-right: -3px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::handle:vertical:hover\n"
"{  \n"
"    height: 11px;\n"
"    background: qradialgradient\n"
"    (\n"
"        spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, \n"
"        stop:0.6 #2A8BDA, stop:0.778409 rgba(255, 255, 255, 255)\n"
"    ); \n"
"    margin-left: -3px;\n"
"    margin-right: -3px;\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QSlider::sub-page:vertical:disabled\n"
"{\n"
"    background: #00009C;\n"
"    border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:vertical:disabled\n"
"{\n"
"    background: #eee;\n"
"    border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:vertical:disabled\n"
"{\n"
"    background: #eee;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 4px;\n"
"}")
        self.page_2.setObjectName("page_2")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(10)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem18)
        self.blurLineEdit = QtWidgets.QLineEdit(self.page_2)
        self.blurLineEdit.setPlaceholderText("")
        self.blurLineEdit.setObjectName("blurLineEdit")
        self.horizontalLayout_11.addWidget(self.blurLineEdit)
        self.horizontalLayout_11.setStretch(0, 1)
        self.horizontalLayout_11.setStretch(1, 8)
        self.horizontalLayout_11.setStretch(2, 1)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.blurHorizontalSlider = QtWidgets.QSlider(self.page_2)
        self.blurHorizontalSlider.setMinimum(0)
        self.blurHorizontalSlider.setMaximum(100)
        self.blurHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.blurHorizontalSlider.setObjectName("blurHorizontalSlider")
        self.verticalLayout_10.addWidget(self.blurHorizontalSlider)
        self.verticalLayout_21.addLayout(self.verticalLayout_10)
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setSpacing(10)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_14 = QtWidgets.QLabel(self.page_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_19.addWidget(self.label_14)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem19)
        self.dilateLineEdit = QtWidgets.QLineEdit(self.page_2)
        self.dilateLineEdit.setPlaceholderText("")
        self.dilateLineEdit.setObjectName("dilateLineEdit")
        self.horizontalLayout_19.addWidget(self.dilateLineEdit)
        self.horizontalLayout_19.setStretch(0, 1)
        self.horizontalLayout_19.setStretch(1, 8)
        self.horizontalLayout_19.setStretch(2, 1)
        self.verticalLayout_19.addLayout(self.horizontalLayout_19)
        self.dilateHorizontalSlider = QtWidgets.QSlider(self.page_2)
        self.dilateHorizontalSlider.setMinimum(0)
        self.dilateHorizontalSlider.setMaximum(100)
        self.dilateHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.dilateHorizontalSlider.setObjectName("dilateHorizontalSlider")
        self.verticalLayout_19.addWidget(self.dilateHorizontalSlider)
        self.verticalLayout_21.addLayout(self.verticalLayout_19)
        self.verticalLayout_20 = QtWidgets.QVBoxLayout()
        self.verticalLayout_20.setSpacing(10)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_15 = QtWidgets.QLabel(self.page_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_20.addWidget(self.label_15)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem20)
        self.erodeLineEdit = QtWidgets.QLineEdit(self.page_2)
        self.erodeLineEdit.setPlaceholderText("")
        self.erodeLineEdit.setObjectName("erodeLineEdit")
        self.horizontalLayout_20.addWidget(self.erodeLineEdit)
        self.horizontalLayout_20.setStretch(0, 1)
        self.horizontalLayout_20.setStretch(1, 8)
        self.horizontalLayout_20.setStretch(2, 1)
        self.verticalLayout_20.addLayout(self.horizontalLayout_20)
        self.erodeHorizontalSlider = QtWidgets.QSlider(self.page_2)
        self.erodeHorizontalSlider.setMinimum(0)
        self.erodeHorizontalSlider.setMaximum(100)
        self.erodeHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.erodeHorizontalSlider.setObjectName("erodeHorizontalSlider")
        self.verticalLayout_20.addWidget(self.erodeHorizontalSlider)
        self.verticalLayout_21.addLayout(self.verticalLayout_20)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setContentsMargins(-1, 10, -1, 10)
        self.verticalLayout_17.setSpacing(10)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_20 = QtWidgets.QLabel(self.page_2)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_25.addWidget(self.label_20)
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem21)
        self.threshComboBox = QtWidgets.QComboBox(self.page_2)
        self.threshComboBox.setObjectName("threshComboBox")
        self.threshComboBox.addItem("")
        self.threshComboBox.addItem("")
        self.threshComboBox.addItem("")
        self.threshComboBox.addItem("")
        self.threshComboBox.addItem("")
        self.horizontalLayout_25.addWidget(self.threshComboBox)
        self.horizontalLayout_25.setStretch(0, 1)
        self.horizontalLayout_25.setStretch(1, 8)
        self.horizontalLayout_25.setStretch(2, 1)
        self.verticalLayout_17.addLayout(self.horizontalLayout_25)
        self.verticalLayout_22 = QtWidgets.QVBoxLayout()
        self.verticalLayout_22.setSpacing(10)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_18 = QtWidgets.QLabel(self.page_2)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_23.addWidget(self.label_18)
        self.threshHorizontalSlider = QtWidgets.QSlider(self.page_2)
        self.threshHorizontalSlider.setMaximum(255)
        self.threshHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.threshHorizontalSlider.setObjectName("threshHorizontalSlider")
        self.horizontalLayout_23.addWidget(self.threshHorizontalSlider)
        self.threshLineEdit = QtWidgets.QLineEdit(self.page_2)
        self.threshLineEdit.setObjectName("threshLineEdit")
        self.horizontalLayout_23.addWidget(self.threshLineEdit)
        self.horizontalLayout_23.setStretch(0, 1)
        self.horizontalLayout_23.setStretch(1, 8)
        self.horizontalLayout_23.setStretch(2, 1)
        self.verticalLayout_22.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_22.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.label_19 = QtWidgets.QLabel(self.page_2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_24.addWidget(self.label_19)
        self.maxvalHorizontalSlider = QtWidgets.QSlider(self.page_2)
        self.maxvalHorizontalSlider.setMaximum(255)
        self.maxvalHorizontalSlider.setSliderPosition(0)
        self.maxvalHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.maxvalHorizontalSlider.setObjectName("maxvalHorizontalSlider")
        self.horizontalLayout_24.addWidget(self.maxvalHorizontalSlider)
        self.maxvalLineEdit = QtWidgets.QLineEdit(self.page_2)
        self.maxvalLineEdit.setObjectName("maxvalLineEdit")
        self.horizontalLayout_24.addWidget(self.maxvalLineEdit)
        self.horizontalLayout_24.setStretch(0, 1)
        self.horizontalLayout_24.setStretch(1, 8)
        self.horizontalLayout_24.setStretch(2, 1)
        self.verticalLayout_22.addLayout(self.horizontalLayout_24)
        self.verticalLayout_17.addLayout(self.verticalLayout_22)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem22)
        self.thresholdResetButton = QtWidgets.QPushButton(self.page_2)
        self.thresholdResetButton.setStyleSheet("QPushButton{\n"
"    border:2px solid;\n"
"    background-color:rgb(255, 255, 255);\n"
"}")
        self.thresholdResetButton.setObjectName("thresholdResetButton")
        self.horizontalLayout_15.addWidget(self.thresholdResetButton)
        self.verticalLayout_17.addLayout(self.horizontalLayout_15)
        self.verticalLayout_21.addLayout(self.verticalLayout_17)
        self.toolBox.addItem(self.page_2, "")
        self.verticalLayout.addWidget(self.toolBox)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem23)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem24)
        self.pushButton = QtWidgets.QPushButton(self.filterPage)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 50))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border:2px solid; \n"
"    background-color:rgb(255, 255, 255)\n"
"}\n"
"QPushButton:pressed{\n"
"\n"
"border:2px solid;\n"
"background-color:rgb(0,0,0);\n"
"color:rgb(255,255,255);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_26.addWidget(self.pushButton)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_26.addItem(spacerItem25)
        self.verticalLayout.addLayout(self.horizontalLayout_26)
        self.stackedWidget.addWidget(self.filterPage)
        self.advancedPage = QtWidgets.QWidget()
        self.advancedPage.setStyleSheet("QPushButton{\n"
"    border:2px solid;\n"
"    background-color:rgb(255, 255, 255);\n"
"}")
        self.advancedPage.setObjectName("advancedPage")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.advancedPage)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, -1, -1, 50)
        self.horizontalLayout_14.setSpacing(20)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.backRemovePushButton = QtWidgets.QPushButton(self.advancedPage)
        self.backRemovePushButton.setMinimumSize(QtCore.QSize(150, 150))
        self.backRemovePushButton.setMaximumSize(QtCore.QSize(150, 150))
        self.backRemovePushButton.setObjectName("backRemovePushButton")
        self.horizontalLayout_14.addWidget(self.backRemovePushButton)
        self.autoContrastPushButton = QtWidgets.QPushButton(self.advancedPage)
        self.autoContrastPushButton.setMinimumSize(QtCore.QSize(150, 150))
        self.autoContrastPushButton.setMaximumSize(QtCore.QSize(150, 150))
        self.autoContrastPushButton.setObjectName("autoContrastPushButton")
        self.horizontalLayout_14.addWidget(self.autoContrastPushButton)
        self.verticalLayout_13.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem26)
        self.label_8 = QtWidgets.QLabel(self.advancedPage)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setStyleSheet("QLabel{\n"
"font-size: 15pt;\n"
"}")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_13.addWidget(self.label_8)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem27)
        self.verticalLayout_13.addLayout(self.horizontalLayout_13)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(10, 20, 10, 20)
        self.gridLayout_5.setVerticalSpacing(30)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pixel32PushButton = QtWidgets.QPushButton(self.advancedPage)
        self.pixel32PushButton.setMinimumSize(QtCore.QSize(100, 100))
        self.pixel32PushButton.setMaximumSize(QtCore.QSize(100, 100))
        self.pixel32PushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-image:url(:/effectImage/effectImage/p32.jpg);\n"
"\n"
"}")
        self.pixel32PushButton.setIconSize(QtCore.QSize(100, 100))
        self.pixel32PushButton.setObjectName("pixel32PushButton")
        self.gridLayout_5.addWidget(self.pixel32PushButton, 0, 0, 1, 1)
        self.pixel48PushButton = QtWidgets.QPushButton(self.advancedPage)
        self.pixel48PushButton.setMinimumSize(QtCore.QSize(100, 100))
        self.pixel48PushButton.setMaximumSize(QtCore.QSize(100, 100))
        self.pixel48PushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-image:url(:/effectImage/effectImage/p48.jpg);\n"
"\n"
"}")
        self.pixel48PushButton.setObjectName("pixel48PushButton")
        self.gridLayout_5.addWidget(self.pixel48PushButton, 0, 1, 1, 1)
        self.pixel64PushButton = QtWidgets.QPushButton(self.advancedPage)
        self.pixel64PushButton.setMinimumSize(QtCore.QSize(100, 100))
        self.pixel64PushButton.setMaximumSize(QtCore.QSize(100, 100))
        self.pixel64PushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-image:url(:/effectImage/effectImage/p64.jpg);\n"
"\n"
"}")
        self.pixel64PushButton.setObjectName("pixel64PushButton")
        self.gridLayout_5.addWidget(self.pixel64PushButton, 1, 0, 1, 1)
        self.pixel128PushButton = QtWidgets.QPushButton(self.advancedPage)
        self.pixel128PushButton.setMinimumSize(QtCore.QSize(100, 100))
        self.pixel128PushButton.setMaximumSize(QtCore.QSize(100, 100))
        self.pixel128PushButton.setStyleSheet("QPushButton{\n"
"color: white;\n"
"background-image:url(:/effectImage/effectImage/p128.jpg);\n"
"\n"
"}")
        self.pixel128PushButton.setObjectName("pixel128PushButton")
        self.gridLayout_5.addWidget(self.pixel128PushButton, 1, 1, 1, 1)
        self.verticalLayout_13.addLayout(self.gridLayout_5)
        spacerItem28 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem28)
        self.stackedWidget.addWidget(self.advancedPage)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.actionWidget)
        self.edit_frame = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_frame.sizePolicy().hasHeightForWidth())
        self.edit_frame.setSizePolicy(sizePolicy)
        self.edit_frame.setMinimumSize(QtCore.QSize(500, 700))
        self.edit_frame.setMaximumSize(QtCore.QSize(1500, 1500))
        self.edit_frame.setStyleSheet("QWidget{\n"
"\n"
"    background-color:rgb(241, 242, 244);\n"
"}")
        self.edit_frame.setObjectName("edit_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.edit_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.canvasTabWidget = QtWidgets.QTabWidget(self.edit_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvasTabWidget.sizePolicy().hasHeightForWidth())
        self.canvasTabWidget.setSizePolicy(sizePolicy)
        self.canvasTabWidget.setMinimumSize(QtCore.QSize(500, 700))
        self.canvasTabWidget.setMaximumSize(QtCore.QSize(1500, 1500))
        self.canvasTabWidget.setToolTip("")
        self.canvasTabWidget.setStyleSheet("#canvasTabWidget{\n"
"    background-color: #171719;\n"
"\n"
"}")
        self.canvasTabWidget.setTabsClosable(True)
        self.canvasTabWidget.setMovable(True)
        self.canvasTabWidget.setTabBarAutoHide(False)
        self.canvasTabWidget.setObjectName("canvasTabWidget")
        self.verticalLayout_2.addWidget(self.canvasTabWidget)
        spacerItem29 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem29)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem30)
        self.comparePushButton = QtWidgets.QPushButton(self.edit_frame)
        self.comparePushButton.setMinimumSize(QtCore.QSize(200, 50))
        self.comparePushButton.setMaximumSize(QtCore.QSize(200, 50))
        self.comparePushButton.setStyleSheet("QPushButton{\n"
"    border:2px solid; \n"
"    background-color:rgb(255, 255, 255)\n"
"}\n"
"QPushButton:pressed{\n"
"\n"
"border:2px solid;\n"
"background-color:rgb(0,0,0);\n"
"color:rgb(255,255,255);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.comparePushButton.setObjectName("comparePushButton")
        self.horizontalLayout_5.addWidget(self.comparePushButton)
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem31)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout.addWidget(self.edit_frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1540, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionOriginalImage = QtWidgets.QAction(MainWindow)
        self.actionOriginalImage.setObjectName("actionOriginalImage")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionChange_Name = QtWidgets.QAction(MainWindow)
        self.actionChange_Name.setObjectName("actionChange_Name")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionGet_Start = QtWidgets.QAction(MainWindow)
        self.actionGet_Start.setObjectName("actionGet_Start")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionsave)
        self.menuHelp.addAction(self.actionGet_Start)
        self.menuEdit.addAction(self.actionOriginalImage)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(1)
        self.canvasTabWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.rotateButton.setToolTip(_translate("MainWindow", "Rotate&Crop"))
        self.drawButton.setToolTip(_translate("MainWindow", "DRAW"))
        self.filterButton.setToolTip(_translate("MainWindow", "Filter"))
        self.effectButton.setToolTip(_translate("MainWindow", "Effect"))
        self.advancedButton.setToolTip(_translate("MainWindow", "Advanced Function"))
        self.drawApplyPushButton.setText(_translate("MainWindow", "Apply"))
        self.drawApplyPushButton.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.label.setText(_translate("MainWindow", "Width"))
        self.label_2.setText(_translate("MainWindow", "Height"))
        self.fixScaleCheckBox.setText(_translate("MainWindow", "Fix Ratio"))
        self.sizePushButton.setText(_translate("MainWindow", "Change"))
        self.rotateRight.setToolTip(_translate("MainWindow", "Rotate Right"))
        self.rotateLeft.setToolTip(_translate("MainWindow", "Rotate Left"))
        self.horizontalPushButton.setToolTip(_translate("MainWindow", "Vertical Flip"))
        self.verticalPushButton.setToolTip(_translate("MainWindow", "Horizontal Flip "))
        self.cropPushButton.setText(_translate("MainWindow", "Crop"))
        self.colorLabel_2.setText(_translate("MainWindow", "Brush Shape"))
        self.penStyleComboBox.setItemText(0, _translate("MainWindow", "SolidLine"))
        self.penStyleComboBox.setItemText(1, _translate("MainWindow", "DashLine"))
        self.penStyleComboBox.setItemText(2, _translate("MainWindow", "DotLine"))
        self.label_3.setText(_translate("MainWindow", "Size"))
        self.penSizeLineEdit.setText(_translate("MainWindow", "5"))
        self.colorLabel.setText(_translate("MainWindow", "Color"))
        self.brightnessPushButton.setText(_translate("MainWindow", "Brightness "))
        self.pencilColorPushButton.setText(_translate("MainWindow", "Pencil"))
        self.gaussianBlurPushButton.setText(_translate("MainWindow", "Gaussian Blur"))
        self.medianBlurPushButton.setText(_translate("MainWindow", "Median Blur"))
        self.sharpPushButton.setText(_translate("MainWindow", "Sharp"))
        self.originalPushButton.setText(_translate("MainWindow", "Original"))
        self.foilPushButton.setText(_translate("MainWindow", "Foil"))
        self.invertPushButton.setText(_translate("MainWindow", "Invert"))
        self.sepiaPushButton.setText(_translate("MainWindow", "Sepia "))
        self.summerPushButton.setText(_translate("MainWindow", "Summer"))
        self.winterPushButton.setText(_translate("MainWindow", "Winter"))
        self.greyScalePushButton.setText(_translate("MainWindow", "GreyScale"))
        self.darkerPushButton.setText(_translate("MainWindow", "Darker"))
        self.hdrPushButton.setText(_translate("MainWindow", "HDR"))
        self.label_5.setText(_translate("MainWindow", "Contrast"))
        self.contrastLineEdit.setText(_translate("MainWindow", "1"))
        self.label_12.setText(_translate("MainWindow", "Hue"))
        self.hueLineEdit.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Brightness"))
        self.brightnessLineEdit.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "Saturation"))
        self.saturationLineEdit.setText(_translate("MainWindow", "0"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Light"))
        self.label_7.setText(_translate("MainWindow", "Blur"))
        self.blurLineEdit.setText(_translate("MainWindow", "0"))
        self.label_14.setText(_translate("MainWindow", "Dilate"))
        self.dilateLineEdit.setText(_translate("MainWindow", "0"))
        self.label_15.setText(_translate("MainWindow", "Erode"))
        self.erodeLineEdit.setText(_translate("MainWindow", "0"))
        self.label_20.setText(_translate("MainWindow", "Threshold"))
        self.threshComboBox.setItemText(0, _translate("MainWindow", "THRESH_TOZERO"))
        self.threshComboBox.setItemText(1, _translate("MainWindow", "THRESH_TOZERO_INV"))
        self.threshComboBox.setItemText(2, _translate("MainWindow", "THRESH_BINARY"))
        self.threshComboBox.setItemText(3, _translate("MainWindow", "THRESH_BINARY_INV"))
        self.threshComboBox.setItemText(4, _translate("MainWindow", "THRESH_TRUNC"))
        self.label_18.setText(_translate("MainWindow", "Thresh"))
        self.threshLineEdit.setText(_translate("MainWindow", "0"))
        self.label_19.setText(_translate("MainWindow", "Maxval"))
        self.maxvalLineEdit.setText(_translate("MainWindow", "0"))
        self.thresholdResetButton.setText(_translate("MainWindow", "Reset"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Details"))
        self.pushButton.setText(_translate("MainWindow", "Reset"))
        self.backRemovePushButton.setText(_translate("MainWindow", "Remove BG"))
        self.autoContrastPushButton.setText(_translate("MainWindow", "Auto Contrast"))
        self.label_8.setText(_translate("MainWindow", "Pixel Style"))
        self.pixel32PushButton.setText(_translate("MainWindow", "32 x 32"))
        self.pixel48PushButton.setText(_translate("MainWindow", "48 x 48"))
        self.pixel64PushButton.setText(_translate("MainWindow", "64 x 64"))
        self.pixel128PushButton.setText(_translate("MainWindow", "128 x 128"))
        self.comparePushButton.setText(_translate("MainWindow", "Compare"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionsave.setText(_translate("MainWindow", "Save"))
        self.actionsave.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.actionOriginalImage.setText(_translate("MainWindow", "Original Image\n"
""))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionChange_Name.setText(_translate("MainWindow", "Change Name"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionGet_Start.setText(_translate("MainWindow", "Get Start"))
import resImg_rc
